---
abstract: 'Provides configurable filtering of data that is logged to the debug logs (and error screen)'
author:
  - 'Brian Phillips <bphillips@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-DebugFilter
requires:
  Catalyst::Runtime: 5.80022
  Clone: 0
  Moose: 0
  namespace::autoclean: 0
version: 0.01
